### PR TITLE
thing: remove hr because it looks bad

### PR DESCRIPTION
**Pull request by teaishealthy**
## Description

The color change already provides a visual separation. No need for an extra hr

## This is a **UI Change**
- [x] This has been previewed and looks as intended

### CODE REVIEW

**Comment by teaishealthy** [comment]
@EnokiUN what's the status on merging this?

**Comment by ashleney** [comment]
Have you considered adding a second hr instead?

**Comment by Sharp-Eyes** [comment]
Perhaps... a third?

**Comment by teaishealthy** [comment]
@Sharp-Eyes @thesadru This is a serious pr, I will not tolerate any goofing around.

**Comment by EnokiUN** [comment]
adding 4 HRs

**Comment by teaishealthy** [comment]
Why was this closed?

**Pull request closed without merging**
